#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: 鑫博客
description: 团结是需要付出代价的

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: //blog.xinxin2021.tk

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /


#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: //s1.imagehub.cc/images/2022/12/21/20c185c419a87ce16d7161a94887440d.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: //www.xinxin2021.tk/blog-favicon.ico


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
  - name: 反馈
    url: //support.qq.com/product/378946

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 网站是否支持IPv6，不支持/不想展示把enable注释掉
ipv6:
  enable: true
  # 0为图标本站已支持IPv6访问 1为图标IPv6 2为自定义文字
  icon: 0
  # 图标是否有边框 0关1开
  # !! 此选项不能在icon为1时开启 !!
  border: 1
  # 自定义文字
  # !! 此选项仅能在icon为2时开启 !!
  text: 本站支持IPv6访问
  # 颜色：1深绿 2浅绿 3深蓝 4浅蓝 5黑 6灰 下面ssl.color同理
  color: 1

# 网站是否支持SSL，不支持/不想展示把enable注释掉
ssl:
  enable: true
  # 0为图标 1为文字
  icon: 0
  # 自定义文字
  # !! 此选项仅能在icon为2时开启 !!
  text: SSL已开启
  color: 1

# ICP备案
icp-record:
  # 不启用把enable注释掉
  #enable: true
  # <京>ICP备XXXXXXXX号
  region: 京
  # 京ICP备<XXXXXXXX>号
  number: XXXXXXXX

# 公安联网备案
public-security-record:
  # 不启用把enable注释掉
  #enable: true
  # <京>公安网备XXXXXXXXXXXXXX号
  region: 京
  # 京公安网备<XXXXXXXXXXXXXX>号
  number: XXXXXXXXXXXXXX

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  email: xinxin@xinxin2021.tk
  facebook: #https://www.facebook.com/<>
  github: xinxin2021
  gitlab: xinxin2021
  instagram: #https://instagram.com/<>
  twitter: xingtehx
  youtube: channel/UC7_GlcEULjU35OIa73inkkg
  telegram: xingteh
  weibo: 7661070283
  zhihu: xinxin-python
  bilibili: 687889425
  qq: 3585097686
  gitee: xinxin-2021
  ixigua: 2454523622734035
  xiaohongshu: 6329dfee000000002303be63
  kuaishou: 3xyuwi6rqfbumm2
  douyin: MS4wLjABAAAA7Hk3D3pmg5jTQdFPqtJtSTkhyMsKZ0NbU0LHPVlA_0Q

# 站点页脚的文字
footer-text: Copyright &copy; 2023 Xinxin

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 默认使用的评论区，每篇文章可单独配置
default-comment: twikoo

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: 

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 63d692e95c5b70ebc3f1
  clientSecret: 0d57c5430d3ca66280e87f587a82221f8114f133
  repo: blog
  owner: xinxin2021
  proxy: //blog-proxy.xinxin2021.tk/github/login/oauth/access_token

# 输入Google Analytics web tracking code
google_analytics: G-Z55V8MJGY8

utteranc:
  repo: # Your github repo path, also see: https://utteranc.es

giscus:
  # 禁用注释enable这行
  enable: true
  # 你要有自己的也可以填自己的
  src: //giscus.app
  # 语言
  lang: zh-CN
  # 主题
  theme: light
  category: Announcements
  categoryID: DIC_kwDOGsTnkc4CXmQw
  repo: blog
  owner: xinxin2021
  repoID: R_kgDOGsTnkQ
  mapping: pathname
  strict: 1
  reactions: 1
  emit-metadata: 0
  input-position: top

twikoo:
  envID: //twikoo.xinxin2021.tk
  

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

