#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: 鑫博客
description: 团结是需要付出代价的

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: //blog.gteh.top

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: 

# 网站是否支持 HTTPS
# 如果你用 https://网站域名 可以访问，那就是 1，否则 0
https: 1

#
# 下面的设定都是可选的
#

# 网页变灰，哀悼用
# 0关1开2永开
gray: 1

# 默认许可协议链接 (识别到 CC 协议时用)
default-cc: //creativecommons.org/licenses/by-nc/4.0/deed.zh-hans

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: //s1.imagehub.cc/images/2022/12/21/20c185c419a87ce16d7161a94887440d.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: //www.gteh.top/blog-favicon.ico

# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about/
  - name: 归档
    url: /archive/
  - name: 标签
    url: /tags/
  - name: 分类
    url: /categories/
  - name: 友链
    url: /friends/
  # 记得把这里改了，别跳转到我的反馈
  - name: 反馈
    url: //support.qq.com/product/

# 友链
friends:
  - name: 测试网站
    link: www.example.com
    url: //www.example.com
    avatar: //www.gteh.top/images/contacts.png
    descr: 测试网站
  - name: 测试网站
    link: www.example.com
    url: //www.example.com
    avatar: //www.gteh.top/images/contacts.png
    descr: 测试网站
    status: 1
    
# 搜索框设置
search:
  placeholder: 搜索博客文章
  no-result: 无结果

# 是否展示阅读量
views: true

# 每页的文章数
paginate: 8

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 是否默认打开MathJax
math: false

# 是否默认打开Mermaid.js
mermaid: false

# 网站是否支持IPv6，不支持/不想展示把enable注释掉
ipv6:
  enable: true
  # 链接
  link: https://blog.gteh.top
  # icon1为图标本站已支持IPv6访问 icon2为图标IPv6 text为自定义文字
  icon: icon2
  # 图标是否有边框 false关true开
  # !! 此选项只能在icon为icon2时关闭 !!
  border: true
  # 自定义文字
  # !! 此选项仅能在icon为2时开启 !!
  #text: 本站支持IPv6访问
  # 颜色：1深绿 2浅绿 3深蓝 4浅蓝 5黑 6灰 下面ssl.color同理
  color: 1

# 网站是否支持SSL，不支持/不想展示把enable注释掉
ssl:
  enable: true
  # 链接
  link: https://blog.gteh.top
  # icon为图标 text为文字
  icon: icon
  # 自定义文字
  # !! 此选项仅能在icon为text时开启 !!
  #text: SSL已开启
  color: 1

# ICP备案
icp-record:
  # 不启用把enable注释掉
  #enable: true
  # <京>ICP备XXXXXXXX号
  region: 京
  # 京ICP备<XXXXXXXX>号
  number: XXXXXXXX

# 公安联网备案
public-security-record:
  # 不启用把enable注释掉
  #enable: true
  # <京>公安网备XXXXXXXXXXXXXX号
  region: 京
  # 京公安网备<XXXXXXXXXXXXXX>号
  number: XXXXXXXXXXXXXX

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  email: gteh@gteh.top
  facebook: #https://www.facebook.com/<>
  github: xinxin2021
  gitlab: xinxin2021
  instagram: #https://instagram.com/<>
  twitter: #https://x.com/<>
  youtube: 
  telegram: #https://t.me/<>
  weibo: 7661070283
  zhihu: xinxin-python
  bilibili: 687889425
  qq: 3585097686
  gitee: xinxin-2021
  ixigua: 2454523622734035
  xiaohongshu: 6329dfee000000002303be63
  kuaishou: 3xyuwi6rqfbumm2
  douyin: MS4wLjABAAAA7Hk3D3pmg5jTQdFPqtJtSTkhyMsKZ0NbU0LHPVlA_0Q

# 站点页脚的文字
footer-text: Copyright &copy; 2023-2024 Xinxin

# 输入Google Analytics web tracking code
google_analytics: G-Z55V8MJGY8

#
# 评论
#

# 默认使用的评论区，每篇文章可单独配置
default-comment: twikoo

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
# disqus.com
# 推荐程度：65% 国内访问不方便 否则90% 免费使用有广告
disqus: xinblog

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
# gitalk.github.io
# 推荐程度：60% 只能用GitHub账号登录 基于GitHub Issues 据说有安全性问题
gitalk:
  clientID: 63d692e95c5b70ebc3f1
  clientSecret: 0d57c5430d3ca66280e87f587a82221f8114f133
  repo: blog
  owner: xinxin2021
  lang: zh-CN
  proxy: //blog-proxy.gteh.top/github/login/oauth/access_token

# utteranc.es
# 推荐程度：70% 类似Gitalk 无安全性问题
utterances:
  repo: xinxin2021/blog

# beaudar.lipk.org
# Utterances中文版 中文博客想使用Utterances建议用这个 无安全性问题
beaudar:
  repo: xinxin2021/blog
  branch: main

# valine.js.org
# 推荐程度：30% 据说有安全漏洞 如果修复推荐程度80%
valine:
  appID: Kn8HIWWLzAMNMSWzHxGRLlEX-MdYXbMMI
  appKey: CzXkIdK2nKxYUXhgWS3ggGd3
  placeholder: "可自动获取 QQ 昵称与头像。当您发表评论后，将由 bot@gteh.top 邮件通知您，务必保证您的邮箱填写正确。"
  lang:
    name: zh-CN
    custom:
      enable: false

# waline.js.org
# 推荐程度：100% 跟Valine类似 无安全漏洞
waline:
  serverURL: https://waline.gteh.top
  requiredMeta: "'nick','mail'"
  login: force
  wordLimit: 500
  turnstileKey: 0x4AAAAAAAJ7bA6swCSRl9mn
  reaction: []
  lang: 
    name: zh-CN
    custom:
      enable: false

# giscus.app
# 推荐程度：75% 类似Gitalk 但基于GitHub Discussions
giscus:
  category: Announcements
  categoryID: DIC_kwDOGsTnkc4CXmQw
  repo: xinxin2021/blog
  repoID: R_kgDOGsTnkQ

# twikoo.js.org
# 推荐程度100%
twikoo:
  # 为了确保在仅HTTP连接的情况下可以访问，其他链接写的都是//开头，这个不行，这个写//会自动侦测为腾讯云envID :(
  envID: https://twikoo.gteh.top
  # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境注释
  #region: ap-guangzhou
  # Twikoo 版本
  version: 1.6.30

#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

